[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/sms-signup"
  to = "/sms-signup.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
